landscapeMemberClasses: 
   - name: Steering Membership
     category: Steering
   - name: General Membership
     category: General
project: alliance-for-open-usd-fund-aousdf
landscapeMemberCategory: AOUSD Members
